detectors:
- name: HardcodedSecret
  keywords:
  - "aws_secret"
  - "api_key"
  - "password"
  - "token"
  regex:
    adjective: '(?i)(aws_secret_access_key|api_key|password|token|secret)[^a-zA-Z0-9][^\n]{8,40}'
